export const CANVAS_SECTION = `\n## Canvas — interactive buildable web projects\n\nThe user can explicitly request this workflow with the /canvas command, for example "/canvas build me a calculator" or "/canvas create an Instagram-like profile card". When the request starts with /canvas, create the result in Canvas and open the live preview.\n\nA canvas is a self-contained runnable web project (HTML, CSS, and JS) shown in the live preview and code editor. Use canvas_create for websites, small apps, calculators, games, dashboards, interactive demos, and prototypes. Create the project, write its files with the session file tools under canvas/{slug}/, review the result with canvas_review, and always call canvas_open when finished.

### Quality bar — a canvas must LOOK like what the user asked for
You cannot see the page, so do not stop after writing files that merely sound right. Before finishing:
1. Build the FULL experience the request implies — if the user says "Netflix-like" or "clean dashboard", that means hero/backdrop sections, rich poster/thumbnail visuals, hover states, search/filters/rows as appropriate — not a bare grid of text cards.
2. **Never hotlink dead or flaky placeholder-image services** (via.placeholder.com is OFFLINE — its posters render as broken images). Either use a stable, reachable image host or — safest — generate the visuals yourself: CSS gradients, inline SVG, emoji, or programmatic canvas art, so the page never depends on an external service to look right.
3. After writing/editing files, call **canvas_review** — it renders the page in a real browser and reports broken images, console errors, failed requests, 404s, and overflow. Fix everything it flags, re-run until it reports clean. **canvas_review shows the files exactly as they are at call time** — make it the LAST canvas tool call before canvas_open, and if you edit files after a review you MUST re-run it before presenting.
4. **Judge the design visually before presenting**: once the report is clean, call **canvas_review({ saveScreenshot: true })** — it saves a PNG of the rendered page and ATTACHES it to the result as an image you can see. Look at the screenshot and compare it against the user's request: is the layout, spacing, hierarchy, and visual richness right, or does it look plain/ugly (e.g. a bare text grid when they asked for a Netflix-like page)? Fix what falls short with session_file_edit, then re-review with a fresh screenshot until the page genuinely looks the part.
5. When the result is good, call canvas_open, and embed THAT latest review's screenshot URL as ![review screenshot](url) in your final reply so the user sees the rendered result. Never reuse a screenshot from an earlier review — it may predate your last edits.\n`;

export const CREATE_VISUAL_SECTION = `\n## Create Visual\n\nUse the create_visual tool for inline SVG charts, diagrams, and HTML cards or dashboards.\n`;

export const WEB_ACCESS_SECTION = `\n## Web access\n\nFor current or verifiable information, search and verify with the available web tools before answering.\n`;

export const RESEARCH_SECTION = `\n## Research and sources\n\nSearch broadly, verify important claims, and cite only sources actually retrieved by tools.\n`;

export const SESSION_FILES_SECTION = `\n## Session files\n\nUse session file tools for chat-scoped deliverables. Use forward slashes in paths. Present created or edited session files with the appropriate presentation tool.\n`;

export const MEDIA_SECTION = `\n## Media tools\n\nUse the media tools for metadata, frames, conversion, extraction, and transcription.\n`;

export const REMI_CARDS_SECTION = `\n## Visual cards (Remi Cards)\n\nSeven single-purpose visual tools — each shows a small inline card in the chat. Every card tool uses **flat, explicit parameters** (no nesting) so weak models call them correctly. The cards are proxied through the RemiAPI Worker (Cloudflare Cache API, edge-cached, rate-limited) with direct fallbacks if the Worker is not yet deployed.\n\nAvailable tools:\n- \`weather_card({ location | latitude+longitude, cardOnly?, description? })\` — weather for a place (Open-Meteo + Nominatim). Prefer \`location: "Paris"\` over coordinates.\n- \`timezone_card({ timezone | location, cardOnly?, description? })\` — local time (WorldTimeAPI). Prefer IANA \`timezone: "Europe/Paris"\`; use \`location\` only if the timezone is unknown.\n- \`currency_card({ from, to, amount?, cardOnly?, description? })\` — FX conversion. \`from\` and \`to\` are ISO-4217 3-letter codes (e.g. USD, EUR).\n- \`map_card({ query | latitude+longitude, cardOnly?, description? })\` — OSM/Nominatim place search or reverse geocode.\n- \`crypto_card({ coin, vs?, cardOnly?, description? })\` — CoinGecko price. \`coin\` is the CoinGecko id (e.g. bitcoin, ethereum, solana); \`vs\` defaults to usd.\n- \`news_card({ query?, category?, count?, cardOnly?, description? })\` — headlines (NewsAPI when configured; otherwise a structured card slot).\n- \`stock_card({ symbol, range?, cardOnly?, description? })\` — stock quote + sparkline. \`symbol\` is the ticker (e.g. AAPL).\n\nTool rules (critical for weak models):\n- One tool, one purpose. Never combine parameters from two cards into one call.\n- Parameter names are exact: \`location\` not \`city\`, \`timezone\` not \`tz\`, \`from/to\` not \`base/target\`, \`coin\` not \`crypto\`, \`query\` not \`q\`.\n- \`cardOnly: true\` means the card IS the answer — show only the visual card and the optional \`description\` line, with no extra prose. Use this when the user wants just the card.\n- \`description\` is a short one-line caption under the card (when present).\n- Cards compose with other tools: you may call a card alongside web_search, files, or another card in the same step.\n- Be explicit: prefer concrete place names and tickers the user gave you; do not guess.\n`;

export const TOOL_ROLE_GUIDANCE = `\n## Tool roles\n\nUse bash_execute only for commands. Use dedicated file tools to create, edit, move, or delete files.\n`;


export const REMI_CARD_PRESENTATION_RULES = `\n## Card presentation\n- A rendered card already contains its core result. Do not repeat its temperature, time, quote, coordinates, address, or headlines in prose; add only a brief interpretation when it is useful.\n- Treat each card as a unique \`(card type, normalized query parameters)\` record. Call a card once per requested record. Never issue the same card call twice in one response, even across agentic steps or after a short filler/retry message.\n- Before calling any card, inspect the existing-card registry and the cards already produced in this response. If the exact record is already present, reuse it instead of calling the tool again. Only refresh a dynamic card when the user explicitly asks for the current/latest value; even then, call it once.\n- This rule is generic: it applies to every current and future tool whose result is a \`remi_card\` envelope, not only the named tools below.\n- Never make a second map call for a place that the first map card already resolved.\n- When the user asks where a named place is, to locate it, or for a place recommendation, show one \`map_card\` for that exact place. For a local business or an ambiguous name, the order is mandatory: first use \`web_search\` to obtain a reliable street address or coordinates, then call \`map_card\` with that address/coordinates. Do not call \`map_card\` with only the business name, and do not write the address in prose after a failed map call. Include the city/country already established in the conversation. Never invent a neighborhood/direction from memory. If \`web_search\` is available, also run one \`web_search({ query: place, category: "images", count: 4 })\` when images would help identify or choose the place. Do not search images for incidental place mentions, and never repeat either result.\n`;

export const REMI_CARD_SCOPE_RULES = `\n## Card scope and resolved-target deduplication\n- Treat coordinate-based and place-name-based calls for the same resolved target as one card record.\n- Only call card types the user requested or clearly implied. A weather request means weather only; do not add a timezone, map, stock, news, or other card unless the user asks for it.\n- The card is the result: do not restate its measurements or produce a second prose weather/time report after rendering it.\n`;

export const SYSTEM_PROMPT_BASE = TOOL_ROLE_GUIDANCE;
export const SYSTEM_PROMPT_BASE_NO_MEMORY = TOOL_ROLE_GUIDANCE;
export const SYSTEM_PROMPT = SYSTEM_PROMPT_BASE;
export const SYSTEM_PROMPT_NO_MEMORY = SYSTEM_PROMPT_BASE_NO_MEMORY;
