import { z } from "zod";
import { chromium, type Browser, type Page } from "playwright";
import { uploadSessionFile, buildSessionFileUrl } from "@/lib/session-files/storage";
import { truncateToolResult } from "@/lib/utils";
import { getWorkServerUrl } from "@/lib/work/execution";

type Session = { browser: Browser; page: Page; mode: "visible" | "headless_fallback"; diagnostics: string[] };
const sessions = new Map<number, Session>();
export async function closeWorkBrowser(runId: number) { const s = sessions.get(runId); sessions.delete(runId); await s?.browser.close().catch(() => {}); }
async function session(runId: number): Promise<Session> { const current = sessions.get(runId); if (current && current.browser.isConnected()) return current; const graphical = process.platform === "darwin" || process.platform === "win32" || Boolean(process.env.DISPLAY); let browser: Browser; let mode: Session["mode"] = "visible"; try { browser = await chromium.launch({ headless: !graphical }); } catch { browser = await chromium.launch({ headless: true, args: ["--no-sandbox"] }); mode = "headless_fallback"; } const page = await browser.newPage({ viewport: { width: 1280, height: 800 } }); const next: Session = { browser, page, mode, diagnostics: [] }; page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") next.diagnostics.push(`console ${m.type()}: ${m.text()}`); }); page.on("requestfailed", (r) => next.diagnostics.push(`request failed: ${r.url()} ${r.failure()?.errorText ?? ""}`)); sessions.set(runId, next); return next; }
function validUrl(runId: number, value: string) { try { const url = new URL(value); return url.hostname === "127.0.0.1" && url.origin === getWorkServerUrl(runId)?.replace(/\/$/, ""); } catch { return false; } }
function snapshot(s: Session) { return { title: s.page.url() ? undefined : "", url: s.page.url(), previewMode: s.mode, diagnostics: s.diagnostics.slice(-50) }; }
/** Bounded, local-only cursor-style visual checks for a Work preview. */
export function buildWorkBrowserTools(conversationId: number, runId: number) { return {
  work_browser_open: { description: "Open the active Work server's 127.0.0.1 preview only. Returns visible-browser status or an explicit headless fallback.", inputSchema: z.object({ url: z.string().url().optional() }), execute: async ({ url }: { url?: string }) => { const target = url ?? getWorkServerUrl(runId); if (!target || !validUrl(runId, target)) return { opened: false, error: "Only the active Work server's 127.0.0.1 URL is allowed." }; const s = await session(runId); await s.page.goto(target, { waitUntil: "domcontentloaded", timeout: 30_000 }); return truncateToolResult({ opened: true, text: (await s.page.locator("body").innerText()).slice(0, 20_000), ...snapshot(s) }); } },
  work_browser_click_at: { description: "Click a coordinate in the active local Work preview.", inputSchema: z.object({ x: z.number().min(0).max(2560), y: z.number().min(0).max(2000) }), execute: async ({ x, y }: { x: number; y: number }) => { const s = await session(runId); await s.page.mouse.click(x, y); return { clicked: true, x, y, ...snapshot(s) }; } },
  work_browser_type: { description: "Type text with the keyboard into the active local Work preview.", inputSchema: z.object({ text: z.string().max(10_000) }), execute: async ({ text }: { text: string }) => { const s = await session(runId); await s.page.keyboard.type(text); return { typed: text.length, ...snapshot(s) }; } },
  work_browser_scroll: { description: "Scroll the active local Work preview by a bounded amount.", inputSchema: z.object({ deltaY: z.number().min(-4000).max(4000) }), execute: async ({ deltaY }: { deltaY: number }) => { const s = await session(runId); await s.page.mouse.wheel(0, deltaY); return { scrolled: deltaY, ...snapshot(s) }; } },
  work_browser_selector: { description: "Click or fill a CSS selector in the active local Work preview.", inputSchema: z.object({ selector: z.string().min(1), value: z.string().optional() }), execute: async ({ selector, value }: { selector: string; value?: string }) => { const s = await session(runId); const loc = s.page.locator(selector).first(); await loc.waitFor({ state: "visible", timeout: 10_000 }); if (value === undefined) await loc.click(); else await loc.fill(value); return { selector, action: value === undefined ? "click" : "fill", ...snapshot(s) }; } },
  work_browser_extract: { description: "Extract rendered DOM text from the active local Work preview, optionally scoped by CSS selector.", inputSchema: z.object({ selector: z.string().optional() }), execute: async ({ selector }: { selector?: string }) => { const s = await session(runId); const text = await s.page.locator(selector ?? "body").first().innerText(); return truncateToolResult({ selector: selector ?? "body", text, ...snapshot(s) }); } },
  work_browser_screenshot: { description: "Save a screenshot plus accumulated console/network diagnostics as Work test evidence.", inputSchema: z.object({ fullPage: z.boolean().optional().default(false) }), execute: async ({ fullPage }: { fullPage?: boolean }) => { const s = await session(runId); const buffer = await s.page.screenshot({ fullPage: fullPage ?? false, type: "png" }); const file = await uploadSessionFile(conversationId, `work-${runId}-${Date.now()}.png`, buffer, "work-evidence"); return { ...snapshot(s), path: file.path, url: buildSessionFileUrl(conversationId, file.path), diagnostics: s.diagnostics.slice(-50) }; } },
  work_browser_close: { description: "Close the Work preview browser after testing.", inputSchema: z.object({}), execute: async () => { await closeWorkBrowser(runId); return { closed: true }; } },
}; }
