"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Activity, Check, Pause, Play, Plus, Search, Trash2, X } from "lucide-react";
import CenteredLayout from "@/components/layout/CenteredLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toolsApi } from "@/lib/api/tools";
import { mcpServersApi, type McpServer } from "@/lib/api/mcp-servers";
import type { ToolWithConfig } from "@/app/api/tools/route";

type Heartbeat = { id: number; name: string; prompt: string; enabled: boolean; schedule: string; nextRunAt: string; allowedToolNames: string[]; allowedToolGroups: string[]; allowedMcpServerIds: number[] };
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Request failed"); return data; }

function PermissionPicker({ options, selected, onAdd, onRemove }: { options: Array<{ value: string; label: string; description?: string; kind: "tool" | "group" | "mcp" }>; selected: Array<{ key: string; label: string; kind: string }>; onAdd: (option: { value: string; label: string; kind: "tool" | "group" | "mcp" }) => void; onRemove: (key: string) => void }) {
  const [query, setQuery] = useState("");
  const matches = useMemo(() => { const selectedKeys = new Set(selected.map((item) => item.key)); return options.filter((option) => !selectedKeys.has(`${option.kind}:${option.value}`) && `${option.label} ${option.description ?? ""}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8); }, [options, query, selected]);
  const add = (option: { value: string; label: string; kind: "tool" | "group" | "mcp" }) => { onAdd(option); setQuery(""); };
  return <div className="space-y-2"><label className="text-sm font-medium">Permissions</label><div className="flex flex-wrap gap-1.5">{selected.map((item) => <span key={item.key} className="inline-flex items-center gap-1.5 rounded-full border bg-muted/60 px-2.5 py-1 text-xs"><span className="text-[10px] uppercase tracking-wide text-muted-foreground">{item.kind}</span><span>{item.label}</span><button type="button" onClick={() => onRemove(item.key)} aria-label={`Remove ${item.label}`}><X size={12} /></button></span>)}</div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && matches[0]) { event.preventDefault(); add(matches[0]); } }} className="h-10 pl-9" placeholder="Search tools, groups, or MCP servers…" />{query && <div className="absolute z-20 mt-1 w-full overflow-hidden rounded-lg border bg-popover shadow-xl">{matches.map((option) => <button type="button" key={`${option.kind}:${option.value}`} onClick={() => add(option)} className="flex w-full items-start gap-3 px-3 py-2.5 text-left text-sm hover:bg-accent"><Check className="mt-0.5 h-4 w-4 opacity-0" /><span><span className="block">{option.label}</span><span className="block text-xs text-muted-foreground">{option.kind} · {option.description}</span></span></button>)}{matches.length === 0 && <p className="px-3 py-2 text-xs text-muted-foreground">No matching permissions</p>}</div>}</div></div>;
}

export default function HeartbeatsPage() {
  const client = useQueryClient(); const [editing, setEditing] = useState<Heartbeat | null>(null); const [name, setName] = useState(""); const [prompt, setPrompt] = useState(""); const [schedule, setSchedule] = useState("3600"); const [tools, setTools] = useState<string[]>(["get_time_details", "web_fetch"]); const [groups, setGroups] = useState<string[]>([]); const [mcpIds, setMcpIds] = useState<string[]>([]);
  const { data } = useQuery({ queryKey: ["heartbeats"], queryFn: () => request<{ heartbeats: Heartbeat[] }>("/api/heartbeats") });
  const { data: toolDefs = [] } = useQuery({ queryKey: ["tools"], queryFn: toolsApi.list });
  const { data: mcpServers = [] } = useQuery({ queryKey: ["mcp-servers"], queryFn: mcpServersApi.list });
  const toolOptions = useMemo(() => toolDefs.flatMap((tool: ToolWithConfig) => tool.toolNames.map((name) => ({ value: name, label: name, description: tool.name }))), [toolDefs]);
  const groupOptions = useMemo(() => toolDefs.map((tool) => ({ value: tool.id, label: tool.name, description: tool.description })), [toolDefs]);
  const mcpOptions = useMemo(() => mcpServers.map((server: McpServer) => ({ value: String(server.id), label: server.name, description: `${server.transport} MCP server${server.enabled ? " · enabled" : " · disabled in MCP settings"}` })), [mcpServers]);
  const permissionOptions = useMemo(() => [...toolOptions.map((option) => ({ ...option, kind: "tool" as const })), ...groupOptions.map((option) => ({ ...option, kind: "group" as const })), ...mcpOptions.map((option) => ({ ...option, kind: "mcp" as const }))], [toolOptions, groupOptions, mcpOptions]);
  const selectedPermissions = useMemo(() => [...tools.map((value) => ({ key: `tool:${value}`, label: value, kind: "tool" })), ...groups.map((value) => ({ key: `group:${value}`, label: value, kind: "group" })), ...mcpIds.map((value) => ({ key: `mcp:${value}`, label: mcpOptions.find((option) => option.value === value)?.label ?? value, kind: "mcp" }))], [tools, groups, mcpIds, mcpOptions]);
  const addPermission = (option: { value: string; label: string; kind: "tool" | "group" | "mcp" }) => { if (option.kind === "tool") setTools((value) => [...value, option.value]); else if (option.kind === "group") setGroups((value) => [...value, option.value]); else setMcpIds((value) => [...value, option.value]); };
  const removePermission = (key: string) => { const [kind, value] = key.split(":"); if (kind === "tool") setTools((items) => items.filter((item) => item !== value)); else if (kind === "group") setGroups((items) => items.filter((item) => item !== value)); else setMcpIds((items) => items.filter((item) => item !== value)); };
  const save = useMutation({ mutationFn: () => request("/api/heartbeats" + (editing ? `/${editing.id}` : ""), { method: editing ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, prompt, scheduleType: "interval", schedule, allowedToolNames: tools, allowedToolGroups: groups, allowedMcpServerIds: mcpIds.map(Number) }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["heartbeats"] }); setEditing(null); setName(""); setPrompt(""); setTools(["get_time_details", "web_fetch"]); setGroups([]); setMcpIds([]); } });
  const action = (id: number, actionName: string) => request<{ message?: string }>(`/api/heartbeats/${id}?action=${actionName}`, { method: "POST" }).then((result) => { if (actionName === "run") toast.success(result.message ?? "Heartbeat started successfully"); return client.invalidateQueries({ queryKey: ["heartbeats"] }); }).catch((error: Error) => { if (actionName === "run") toast.error(error.message || "Could not start Heartbeat"); });
  const remove = (id: number) => request(`/api/heartbeats/${id}`, { method: "DELETE" }).then(() => client.invalidateQueries({ queryKey: ["heartbeats"] }));
  const beginEdit = (item: Heartbeat) => { setEditing(item); setName(item.name); setPrompt(item.prompt); setSchedule(item.schedule); setTools(item.allowedToolNames); setGroups(item.allowedToolGroups ?? []); setMcpIds((item.allowedMcpServerIds ?? []).map(String)); };
  return <CenteredLayout><div className="flex max-w-3xl w-full flex-col gap-6"><div><div className="flex items-center gap-2"><Activity className="h-5 w-5" /><h1 className="text-lg font-semibold">Heartbeats</h1></div><p className="mt-1 text-sm text-muted-foreground">Autonomous AI jobs that run on the server while RemiAI is running, without a chat or connected browser.</p></div>
    <Card className="p-4 space-y-4"><h2 className="font-medium">{editing ? "Edit Heartbeat" : "Create Heartbeat"}</h2><Input placeholder="Name" value={name} onChange={(event) => setName(event.target.value)} /><textarea className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm" placeholder="What should the AI do?" value={prompt} onChange={(event) => setPrompt(event.target.value)} /><PermissionPicker options={permissionOptions} selected={selectedPermissions} onAdd={addPermission} onRemove={removePermission} /><div className="flex items-end justify-between gap-3 border-t pt-4"><div className="space-y-1"><label className="text-xs font-medium text-muted-foreground">Run every</label><div className="flex items-center gap-2"><Input className="h-9 w-28" type="number" min={60} value={schedule} onChange={(event) => setSchedule(event.target.value)} /><span className="text-xs text-muted-foreground">seconds</span></div></div><Button onClick={() => save.mutate()} disabled={!name || !prompt || save.isPending}>{editing ? "Save" : <><Plus className="mr-1 h-4 w-4" />Create</>}</Button></div><p className="text-xs text-muted-foreground">Only selected permissions are available to this Heartbeat. Type to search; press Enter or click a result to add it.</p></Card>
    <div className="space-y-3">{(data?.heartbeats ?? []).map((item) => <Card key={item.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><Activity className={item.enabled ? "text-emerald-500" : "text-muted-foreground"} size={16} /><h2 className="font-medium">{item.name}</h2><span className="text-xs text-muted-foreground">{item.enabled ? "Active" : "Paused"}</span></div><p className="mt-2 text-sm whitespace-pre-wrap">{item.prompt}</p><p className="mt-2 text-xs text-muted-foreground">Every {item.schedule} seconds · Next run {new Date(item.nextRunAt).toLocaleString()} · {item.allowedToolNames.length} tools allowed</p></div><div className="flex gap-1"><Button size="icon-sm" variant="ghost" onClick={() => action(item.id, "run")} title="Run now"><Play size={15} /></Button><Button size="icon-sm" variant="ghost" onClick={() => action(item.id, item.enabled ? "pause" : "resume")} title={item.enabled ? "Pause" : "Resume"}>{item.enabled ? <Pause size={15} /> : <Play size={15} />}</Button><Button size="sm" variant="ghost" onClick={() => beginEdit(item)}>Edit</Button><Button size="icon-sm" variant="ghost" onClick={() => remove(item.id)}><Trash2 size={15} /></Button></div></div></Card>)}</div>
  </div></CenteredLayout>;
}
